### ISSUE TITLE
How to add a confirmation popup before deleting a record

### ISSUE THREAD

**Issue by rahulcs1988ai** [CarlosNZ/json-edit-react#100]
is there any method to override the onDelete functionality so that I can show a confirmation popup before deleting a record

**Comment by CarlosNZ** [comment]
Yes, you just pass in your function as the `onDelete` prop. Your function should return `false` or an error string if it shouldn't do the delete action, and nothing if it should proceed as normal. Something like:

```js
onDelete={
  ( {name} ) => {
     const result = confirm(`Are you sure you want to delete ${name}?`)
     if (result === false) return false  // The data won't be updated
     else return  // The data will be updated
  }
}
```

See [Update functions](https://github.com/CarlosNZ/json-edit-react?tab=readme-ov-file#update-functions) for more detail. 

Hope that helps.

**Comment by rahulcs1988ai** [comment]
@CarlosNZ Thank you so much :)
