### ISSUE TITLE
能否添加自定义操作，感谢大佬

### ISSUE THREAD

**Issue by suyizhang** [CarlosNZ/json-edit-react#102]
Hello master, now there are copy, delete, edit and other operation buttons after each data item. Can you support custom operation buttons? You can customize the icon or use the built-in icon to receive a method that takes the key value of the current data and the entire data as input parameters

**Comment by CarlosNZ** [comment]
There are a couple of ways you could do what something close to what you're asking, depending on your use case.

1. You can add an "onCopy" function to the "Copy" button to perform some additional action (pass function to the `enableClipboard` prop: https://github.com/CarlosNZ/json-edit-react?tab=readme-ov-file#copy-function)
2. Make a [Custom Node](https://github.com/CarlosNZ/json-edit-react?tab=readme-ov-file#custom-nodes) and put your own button inside it.

I might make it a little easier to keep existing content in Custom nodes, so it's simple to add your own content.

**Comment by suyizhang** [comment]
Thank you for your response. Modifying 'onCopy' may not be suitable for my scenario. I will try using the custom component you recommended

**Comment by CarlosNZ** [comment]
Good to hear, please let me know if you have any problems or have suggestions to make it easier.

**Comment by suyizhang** [comment]
Custom components cannot add custom operations. Can parameters be added to increase the operation buttons within the EditButtons component
for example
<img width="884" alt="image" src="https://github.com/user-attachments/assets/93b847a2-f104-406b-9002-def9b7e6f04c">
