### ISSUE TITLE
huge data insert, and cause the operation to be very slow

### ISSUE THREAD

**Issue by JoeYnnn** [CarlosNZ/json-edit-react#107]
When I convert huge amounts of data, such as more than tens of thousands of lines of data, this will cause the operation to be very slow after the conversion, and chrome sees that the web page takes up several G's

**Comment by CarlosNZ** [comment]
Well yeah, if it's a massive data set, the render tree is going to be pretty large/slow.

There is one performance improvement I've added that you can take advantage of, though. The component doesn't render child elements until the first time they are *visible*. So if you set the default `collapse` level to `1` (or even `0`), the initial render is pretty fast if the top level doesn't have too many elements.

Any chance you could share your data set (if it's not private information)? Kind of keen to try it out.

But yeah, for truly massive data structures, this is probably not the right tool for the job. I would say something like the ["Star Wars" data set in my demo](https://carlosnz.github.io/json-edit-react/?data=starWars) is about the maximum you'd reasonably expect to work with in this way.

**Comment by CarlosNZ** [comment]
Closing, as this doesn't seem like an actual problem. It's behaving as expected for what it is, as far as I can tell.
