### ISSUE TITLE
Request to change dependencies to MIT license

### ISSUE THREAD

**Issue by sree-deep** [CarlosNZ/json-edit-react#108]
**Describe the bug**
Hello, We wish to use json-edit-react package for our project with MIT license. But the dependent packages are still on GPL3, so we are unable to use json-edit-react ->
1. https://www.npmjs.com/package/object-property-extractor
2. https://www.npmjs.com/package/object-property-extractor

Could you please convert these package licenses to MIT?

Thanks!

**Comment by CarlosNZ** [comment]
Oh, I thought I already had. But I see now that only shows on the [NPM page](https://www.npmjs.com/package/object-property-extractor), not in the [Github repo.](https://github.com/CarlosNZ/object-property-extractor). 

Sure, I'll definitely update those, thanks for pointing it out. Check back in a day or two.

**Comment by sree-deep** [comment]
Thanks a lot!

**Comment by CarlosNZ** [comment]
Hi there @sree-deep , this is all updated now -- latest release uses the MIT licensed versions of those packages: https://www.npmjs.com/package/json-edit-react/v/1.15.9

Thanks for pointing this out.
