### ISSUE TITLE
Make the entire node clickable

### ISSUE THREAD

**Issue by pankajparashar** [CarlosNZ/json-edit-react#118]
It'll be nice for the entire node to be clickable, instead of just using the Arrow icons to expand/collapse a node. Also it will make it more accessible.

Even if the library doesn't want to support this, Can you guide me how I can implement this using your library?

**Comment by CarlosNZ** [comment]
Thanks for the suggestion. It's not a bad idea as the current click zone is possibly a bit small, particularly on mobile devices.

It's fairly simple to add the click handler to the whole `div`, but making it _not_ respond to the other click zones is a bit trickier, not to mention possible conflicts with drag and drop.

I'll need to have a think about how best to implement it so it doesn't seem confusing if you're not expecting it, but I think we can do something. Perhaps just the whole left margin could be the click zone?

Open to further discussion.

**Comment by CarlosNZ** [comment]
@pankajparashar What do you think of this? I've made a "click-zone" down the whole left margin of the node, as well as made the main header bar click-able for collapse:

![2024-09-10 11 40 41](https://github.com/user-attachments/assets/b54adc40-f775-47e4-bb12-348d5e39c4a9)

I think this is nicer than making literally the whole node clickable, as it's a bit more intuitive for the user and won't conflict with drag-n-drop and other clickable items (e.g. double-click to edit)

**Comment by pankajparashar** [comment]
Yes I think this looks perfect! Massive thanks for adding this feature!
