### ISSUE TITLE
Bug report - Unexpected Node Collapsing Upon Confirm Button Click

### ISSUE THREAD

**Issue by roman-simionov** [CarlosNZ/json-edit-react#123]
**Describe the bug**

Hi,

I've encountered an issue while attempting to add a new node to JSON.

version 1.16.0

Steps to Reproduce:

1. Open [the demo](https://carlosnz.github.io/json-edit-react).
2. Click the Add button on the root node.
3. Enter a name for the new node.
4. Click the Confirm button.

**Current behavior**
The root node collapses unexpectedly.

**Expected behavior**
The root node should remain expanded after adding a new child node.

[This video](https://github.com/user-attachments/assets/42d007ba-3095-4382-84ef-e06f0cc77507) demonstrates the problem

**Comment by CarlosNZ** [comment]
Ah okay, thanks. I [made a change recently](https://github.com/CarlosNZ/json-edit-react/issues/118) to expand the clickable area for collapsing and had to make sure existing clicks didn't "fall through" and register a collapse click. But it looks like I missed one 😳, so thanks for pointing out. Look for a fix in the next few days :)

**Comment by CarlosNZ** [comment]
@roman-simionov -- this is now fixed in [v1.16.3](https://www.npmjs.com/package/json-edit-react/v/1.16.3)

Thanks for bringing it to my attention 👍
