### ISSUE TITLE
defaultValue function doesn't get newly added key in any of the params.

### ISSUE THREAD

**Issue by yaswanthmaddula-sureify** [CarlosNZ/json-edit-react#124]
**Describe the bug**

I added a new key in the editor, the defaultValue function is called, but it doesn't have the new key that i added. 

**Expected behavior**
If the new key that i added is available in the `key` param, then it would have been handy to set a default value for the same.

**Screenshots**

**Online demo**
https://codesandbox.io/p/sandbox/json-edit-react-demo-forked-pmwxjt?file=%2Fsrc%2FApp.js%3A28%2C25

maybe something like this will be helpful.
![image](https://github.com/user-attachments/assets/2882cc82-94ca-4cb8-baa5-27659fe70a6b)

**Comment by CarlosNZ** [comment]
Yes, I see what you mean. I guess that would be fairly straightforward to add. I'll try and get this in soon.

Thanks for the suggestion

**Comment by CarlosNZ** [comment]
Hi @yaswanthmaddula-sureify -- this is available now in [v1.17.0](https://www.npmjs.com/package/json-edit-react/v/1.17.0)

**Comment by yaswanthmaddula-sureify** [comment]
Thanks for the fix. Looks like the release is not published in github yet @CarlosNZ

**Comment by CarlosNZ** [comment]
> Looks like the release is not published in github yet @CarlosNZ

Right, it's there now: https://github.com/CarlosNZ/json-edit-react/releases/tag/v1.17.0

I didn't realise people actually use the Releases, thought it was just the npm packages.
