### ISSUE TITLE
Add new property not in the end

### ISSUE THREAD

**Issue by CarlosNZ** [CarlosNZ/json-edit-react#132]
### Discussed in https://github.com/CarlosNZ/json-edit-react/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **Set27** December 13, 2024</sup>
Is it possible?
I don't see ways how to implement it.</div>

**Comment by CarlosNZ** [comment]
Will consider adding as an option.

**Comment by CarlosNZ** [comment]
Hi @Set27, you can now do this in [v1.18.0](https://www.npmjs.com/package/json-edit-react/v/1.18.0)

Use the `insertAtTop` prop, as detailed [here](https://github.com/CarlosNZ/json-edit-react?tab=readme-ov-file#props-overview)

**Comment by Set27** [comment]
> Hi @Set27, you can now do this in [v1.18.0](https://www.npmjs.com/package/json-edit-react/v/1.18.0)
> 
> Use the `insertAtTop` prop, as detailed [here](https://github.com/CarlosNZ/json-edit-react?tab=readme-ov-file#props-overview)

Thank you for your work. 
But do you consider option, to have custom field where I can choose between what elements I can insert new property?

**Comment by CarlosNZ** [comment]
> But do you consider option, to have custom field where I can choose between what elements I can insert new property?

Can you give me an example?

**Comment by Set27** [comment]
> > But do you consider option, to have custom field where I can choose between what elements I can insert new property?
> 
> Can you give me an example?

Let's imagine I have an array of 5 elements.
I want to add a new element in between the third and fourth elements

**Comment by CarlosNZ** [comment]
> Let's imagine I have an array of 5 elements.
> I want to add a new element in between the third and fourth elements

Are you suggesting having that in the UI for the user to select? You can always use [drag-n-drop](https://github.com/CarlosNZ/json-edit-react?tab=readme-ov-file#drag-n-drop) to move it to where you want. 

Or are you wanting to configure it in the code?
