### ISSUE TITLE
Confirm with cmd+enter instead of enter key

### ISSUE THREAD

**Issue by DameNianch** [CarlosNZ/json-edit-react#133]
As the title says, I want to confirm with cmd+enter instead of enter key. If there is a way to do this, please let me know. If not, I would like the feature to be added. I'm not confident about the code quality, but I can submit a PR.

The following are the reasons for this feature request.

Confirming with the enter key is problematic for many Japanese people. In Japanese, 3-7 types of characters are mainly used: hiragana, katakana, kanji, and alphabet (x2-4). After entering text on the keyboard, the user selects which type to use. Since the enter key is used to select, if the text is confirmed with the enter key, it is frustrating because you cannot continue entering text. I have expressed a specific example of the operation in text.

When typing 
"CarlosNZは偉大なengineerです"
It need to type
"CarlosNZ" "は" "enter" "偉大な" "enter" "engineer" "です" "enter"

ref: https://github.com/CarlosNZ/json-edit-react/blob/10f5c9fe3c28154fbafa9c633863695d3c85d5aa/src/ValueNodes.tsx#L23

**Comment by CarlosNZ** [comment]
Thanks for the suggestion. You currently use Cmd-Enter when editing the multiline/JSON blocks so that you can add line breaks in the text, but plain old Enter for simple inputs.

I should be able to make the "Confirm" key a customisable option fairly easily. I'll try and do that in the next week or so.

**Comment by DameNianch** [comment]
> You currently use Cmd-Enter when editing the multiline/JSON blocks so that you can add line breaks in the text,

I feel like that's a bit misleading, so let me clarify. In this multi-line editing, you can confirm with Cmd-Enter. The Enter key is treated as adding a line.
https://github.com/CarlosNZ/json-edit-react/blob/10f5c9fe3c28154fbafa9c633863695d3c85d5aa/src/CollectionNode.tsx#L130
<img width="535" alt="スクリーンショット 2024-12-13 12 11 05" src="https://github.com/user-attachments/assets/d1e447fb-c00f-4771-8ec6-baf8c5f50648" />

On the other hand, when inputting strings only (is this simple inputs?), Cmd+Enter is treated as just Enter. Shift-Enter creates a new line.
https://github.com/CarlosNZ/json-edit-react/blob/10f5c9fe3c28154fbafa9c633863695d3c85d5aa/src/ValueNodes.tsx#L23
<img width="521" alt="スクリーンショット 2024-12-13 12 14 25" src="https://github.com/user-attachments/assets/60f9a95e-3f13-4bbd-922b-bf510ad33c4f" />

**Comment by CarlosNZ** [comment]
> On the other hand, when inputting strings only (is this simple inputs?), Cmd+Enter is treated as just Enter. Shift-Enter creates a new line.

Yes, that is correct, I forgot 🙄

I'll make it so you can override as many or few of the keyboard controls as you wish, by passing in an object like this:

```ts
export interface KeyEvent {
  key: string
  modifier?: string | string[]
}

export interface KeyboardShortcuts {
  confirm?: KeyEvent | string // buttons, and value node default
  cancel?: KeyEvent | string // all "Cancel" operations
  objectConfirm?: KeyEvent | string
  objectLineBreak?: KeyEvent | string
  stringConfirm?: KeyEvent | string
  stringLineBreak?: KeyEvent | string // for Value nodes
  numberConfirm?: KeyEvent | string
  booleanConfirm?: KeyEvent | string
  numberUp?: KeyEvent | string
  numberDown?: KeyEvent | string
  clipboardModifier?: string | string[]
  collapseModifier?: string | string[]
}
```

**Comment by DameNianch** [comment]
Thank you. That feels so good.
I'm looking forward to the fix!!

**Comment by CarlosNZ** [comment]
Hi @DameNianch, I've made a PR for this and published a beta to npm if you'd like to give it a try:

https://www.npmjs.com/package/json-edit-react/v/1.18.0-beta1

Documentation added to README here: https://github.com/CarlosNZ/json-edit-react/blob/133-keyboard-overrides/README.md#keyboard-customisation

**Comment by DameNianch** [comment]
@CarlosNZ 

I'm very grateful for your quick response.
I just installed it and checked that it works.
The coding remains cool, and it's friendly to Japanese people, which I like even more.

**Comment by CarlosNZ** [comment]
> I'm very grateful for your quick response. I just installed it and checked that it works. The coding remains cool, and it's friendly to Japanese people, which I like even more.

Glad to hear, it was a good suggestion.
