### ISSUE TITLE
json-edit-react/src/styles.css is not reflected in new window.

### ISSUE THREAD

**Issue by DameNianch** [CarlosNZ/json-edit-react#135]
**Describe the bug**
As the title says, json-edit-react/src/styles.css is not reflected in another window. Below is the source code.

```
import React, { useEffect, useRef } from "react";
import ReactDOM from "react-dom";
import { JsonEditor } from "json-edit-react";

interface PropsWindowProps {
  shownProps: object;
  onClose: () => void;
}

const PropsWindow: React.FC<PropsWindowProps> = ({ shownProps, onClose }) => {
  const newWindow = useRef<Window | null>(null);
  const containerEl = document.createElement("div");

  useEffect(() => {
    newWindow.current = window.open("", "_blank", "width=1200,height=800");
    if (newWindow.current) {
      newWindow.current.document.body.appendChild(containerEl);

      const handleUnload = () => {
        onClose();
      };
      newWindow.current.addEventListener("beforeunload", handleUnload);

      return () => {
        newWindow.current?.removeEventListener("beforeunload", handleUnload);
        newWindow.current?.close();
      };
    }
  }, [containerEl, onClose]);

  return ReactDOM.createPortal(
    <div>
      <JsonEditor data={shownProps} />
    </div>,

    containerEl
  );
};

export default PropsWindow;

```

**Expected behavior**

CSS, including flex, is applied. This screenshot shows the result of displaying JsonEditor in the same (parent/main) window.
<img width="1510" alt="スクリーンショット 2024-12-17 11 29 36" src="https://github.com/user-attachments/assets/cbd0e423-17a5-46bf-ada3-4d13b5235dba" />

**Screenshots**
<img width="2118" alt="スクリーンショット 2024-12-17 11 35 21" src="https://github.com/user-attachments/assets/89fb1988-735d-46fa-a4de-998d5a1d34b5" />

**Online demo**
https://codesandbox.io/p/sandbox/json-edit-react-demo-forked-mlsn6f?workspaceId=ws_CTwx66TnRUb2vkBSHCXygH

**Comment by CarlosNZ** [comment]
Interesting, I'll take a look into it. Unusual situation, but worth figuring out what's going on. Thanks.

**Comment by DameNianch** [comment]
Thank you for your quick response.

I just found the solution. https://stackoverflow.com/questions/73630464/could-not-apply-css-on-react-portal-content

When I applied what was written here, the style was applied. I updated the codesandbox and posted a failure example and a success example. I hope that people who reach here don't have the same problem.

**Comment by CarlosNZ** [comment]
Okay, so this isn't actually a problem with this component, it's just a consequence of the way the new window is opened and the how React works with it.

The solution is you have to manually copy the styles (and other things) from the parent window to the child.

I tried the answer suggested here, and it worked: https://stackoverflow.com/a/68989787

Here is my modified sandbox with it working as desired: https://codesandbox.io/p/sandbox/json-edit-react-demo-forked-xzx5hq?workspaceId=ws_WnssZ3DHwX7dk5S788GZBn

Good luck, hope you get it doing what you need. 

I'm going to close this now, as I'm fairly confident it's not a bug with this component.

**Comment by CarlosNZ** [comment]
Ha, I see you posted back just before I replied 😆

Looks like you found a similar solution!
