### ISSUE TITLE
DateTimePicker display is distorted.

### ISSUE THREAD

**Issue by DameNianch** [CarlosNZ/json-edit-react#137]
**Describe the bug**
In the demo page below, the component that appears when you select a date (created) is distorted, as shown in the attached image.
 https://carlosnz.github.io/json-edit-react/?data=starWars

**Expected behavior**
Not distorted.

**Screenshots**
<img width="558" alt="スクリーンショット 2024-12-18 13 47 37" src="https://github.com/user-attachments/assets/55682dc9-11a7-4686-bd26-e624db1d4793" />

**Online demo**
Nothing.

**Comment by DameNianch** [comment]
From reading the source code, the DateTimePicker looks like for the demo. I'm sorry if date selection is not supported by `json-edit-react`.

https://github.com/CarlosNZ/json-edit-react/blob/main/demo/src/customComponents/DateTimePicker.tsx

**Comment by CarlosNZ** [comment]
Interesting, it looks fine for me. What browser/OS are you using?
![Screenshot 2024-12-18 at 6 00 15 PM](https://github.com/user-attachments/assets/cdfd8e37-fe42-4fff-b2b5-7ce9c2042549)

**Comment by CarlosNZ** [comment]
> From reading the source code, the DateTimePicker looks like for the demo. I'm sorry if date selection is not supported by

Yeah, the DateTimePicker is a custom component, not part of the core package. Still, I'd like the demo to look correct everywhere. :)

**Comment by DameNianch** [comment]
Thank you again today.

> What browser/OS are you using?

browser: chrome 131.0.6778.86（Official Build） （arm64）
OS: macOS Sonoma 14.5
