### ISSUE TITLE
Adding to an array doesn't seem to work

### ISSUE THREAD

**Issue by pawelzygmuntowski** [CarlosNZ/json-edit-react#30]
Hi, I can't seem to get the Add button to work on properties that are arrays. I can edit the whole array using the edit button and adding the values in the text editor there. But when I press the Add button on any array property to add to it, I'm getting an error.
`json-edit-react.js?t=1707483740439&v=3e66a0aa:18 Uncaught (in promise) Error: Invalid property path: test.arr[3]
Couldn't access "3" in {"test":{"arr":[1,0,0]}}
    at r (json-edit-react.js?t=1707483740439&v=3e66a0aa:18:11)
    at l (json-edit-react.js?t=1707483740439&v=3e66a0aa:74:28)
    at i (json-edit-react.js?t=1707483740439&v=3e66a0aa:43:95)
    at i (json-edit-react.js?t=1707483740439&v=3e66a0aa:57:5)
    at i (json-edit-react.js?t=1707483740439&v=3e66a0aa:57:5)
    at o (json-edit-react.js?t=1707483740439&v=3e66a0aa:31:57)
    at updateDataObject (json-edit-react.js?t=1707483740439&v=3e66a0aa:674:40)
    at json-edit-react.js?t=1707483740439&v=3e66a0aa:661:62
    at Generator.next (<anonymous>)
    at json-edit-react.js?t=1707483740439&v=3e66a0aa:288:67`
    
 It's trying to access "3" which is exactly what I'm trying to add, so it doesn't exist yet. 
 The adding with plus/add icon works on objects, but not on arrays. Is it some kind of bug, or am I doing something wrong? It doesn't work even in the simplest case like the one I'm showing though.

**Comment by CarlosNZ** [comment]
Hi, thanks for letting me know, I'll take a look. 

Which version of React are you using, and browser?

Also, can you confirm that you can add array elements okay in the online demo? https://carlosnz.github.io/json-edit-react/

**Comment by pawelzygmuntowski** [comment]
Very strange, it definitely works in the online demo. I'm using Google Chrome (latest) and react 18.2.0.
The json in my example is very simple, but it doesn't work. Is it dependent on a specific configuration or prop setup?

**Comment by CarlosNZ** [comment]
> The json in my example is very simple, but it doesn't work. Is it dependent on a specific configuration or prop setup?

You need to make sure your `onUpdate` prop is updating your data state correctly outside the JsonEditor. I may not have made this clear enough in the docs, as it didn't used to strictly be this way (I will update).

In other words, something like:

```jsx
// Inside React component...
const [data, setData] = useState({myData:[1,2,3,4]})

return <JsonEditor data={data} onUpdate={ ({newData}) => setData(newData)} {...otherProps} />

```

Does that help? 

If not, I'm going to release an update in a day or two with some improvements, so see if that helps.

Otherwise, you might need to post a bit more of your code and I'll take a closer look.

**Comment by pawelzygmuntowski** [comment]
Hmm, that's very strange. Because even this very minimalistic example you provided above doesn't work for me.
I did console.logs inside the code of the package, for the `updateDataObject` function.
<img width="472" alt="Zrzut ekranu 2024-02-14 o 13 00 06" src="https://github.com/CarlosNZ/json-edit-react/assets/70859525/b1dc43f5-4a32-4dc9-9231-9bc08548ac86">

This is the result for exactly the code from above, the simplest case, where onUpdate is setting the data and the data is exactly like in the example, just a simple useState.
It would seem (I'm just guessing, since it's hard for me to understand all the code of the package, like the problem stems from it having path ['myData', 4] and index 4 not existing yet?

I wonder why it works in the online demo, but it doesn't work for me..

**Comment by CarlosNZ** [comment]
Can you try the latest version (1.3.2)?

I've modified it so that it will update the internal state of `data` even if you don't update it from outside. So you should see a working example with just:

```jsx
return <JsonEditor data={{myData:[1,2,3,4]}} {...otherProps} />
```

If that works, then see what happens when updating `data` yourself using `onUpdate`.

**Comment by CarlosNZ** [comment]
Hi there @pawelzygmuntowski,

can you try the latest version (1.6.0) and see if that helps at all? If not, would you be able to fork my sandbox at [codesandbox](https://codesandbox.io/p/sandbox/json-edit-react-demo-g5qlym?file=%2Fsrc%2FApp.js%3A11%2C11) and see if you can reproduce the problem in there?

**Comment by CarlosNZ** [comment]
Closing issue -- please re-open with example code if problem persists.
