### ISSUE TITLE
Minor issue with <label>

### ISSUE THREAD

**Issue by maxpaleo** [CarlosNZ/json-edit-react#47]
Minor issue, but it would be useful to fix it to prevent the browser from throwing errors. 
The keys are rendered using a `<label/>` element, which has a `for` property, but the value doesn't specify the matching ID; causing warnings.

**Screenshots**
<img width="1325" alt="Screenshot 2024-04-28 at 10 37 12 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/91980500/25928cf6-dd00-4f35-b08c-022ee1180e40">

**Comment by CarlosNZ** [comment]
Yeah, sure, can fix that. Thanks for pointing it out. Look for an update in a day or two.

**Comment by CarlosNZ** [comment]
Fix coming in next release (in the next day or so).

I've just turned the `<label>` elements into `<span>s`, as there is no static connection between the label and its input, so the `for` attribute is not helping at all.

**Comment by CarlosNZ** [comment]
Should be fixed in 1.9.0 -- available now :)

**Comment by maxpaleo** [comment]
Perfect, thanks!
