### ISSUE TITLE
Too long string breaks UI and rendering 

### ISSUE THREAD

**Issue by V3RGANz** [CarlosNZ/json-edit-react#57]
For this example json, lets edit `d1->text1` value and put some very big string into it: 
```json
{
  "d1": {
    "text1": "This is text1",
    "text2": "This is text1"
  },
  "d2": {
    "name": "name-of-something",
    "args": {
      "some_key": "some-val"
    }
  },
  "next": {
    "kkk": "v-v-v"
  }
}
```

**Expected behavior**
- All elements below will be shifted no matter length of the string
- Other elements will not interfere while string in edit mode

**Demo from https://carlosnz.github.io/json-edit-react/**

https://github.com/CarlosNZ/json-edit-react/assets/14924440/6116883c-9844-4dde-8a9a-5d6b20fec40b

**Comment by CarlosNZ** [comment]
Yeah, thanks for bring this up. I think it's due to the hacky way I've had to handle the height of the elements. The CSS collapse animation doesn't work with `height: auto`, so I've had to set a `maxHeight` which is calculated dynamically using a fairly crude metric. 

I'll need to rethink this a bit, will keep you posted.

**Comment by V3RGANz** [comment]
By the way, I don't think the positioning of other elements is the main problem. If the current text area were the top layer, it would be still usable.

**Comment by CarlosNZ** [comment]
Hi @V3RGANz, I've fixed this now and it's working well for both editing and non-editing display. 

I've added an additional restriction that only one element can be "editing" at a time (made the logic for handling the dynamic height much cleaner).

I need to do a bit more testing and tweaking, but I'll put a release out before the end of this weekend.

**Comment by CarlosNZ** [comment]
Righto, this should be sorted in v10.0.2 now. Please let me know if you find any other problems.

Cheers :)
