### ISSUE TITLE
Long string with no spaces should wrap

### ISSUE THREAD

**Issue by KungFuCookie** [CarlosNZ/json-edit-react#58]
**Describe the bug**
When a string value is a JWT token or something similar

**Expected behavior**
The string is breaking out of the Parent container. It should really wrap to a new line.

**Potential Fix**
I added a small css hack which solve the issue but should probably be added to the default css.
```
.jer-value-string {
  overflow-wrap: anywhere;
}
```
![image](https://github.com/CarlosNZ/json-edit-react/assets/43062388/b69cf553-7e54-4207-aef2-4b007874d8d9)

Great work though buddy!!

**Comment by CarlosNZ** [comment]
Sure thing, I'll try and get that sorted. Thanks for pointing it out.

**Comment by CarlosNZ** [comment]
Okay, this should be fixed now in v10.0.2. Thanks, I used your suggestion.
