### ISSUE TITLE
Empty string is a valid object key but is not allowed nor parsed correctly as input

### ISSUE THREAD

**Issue by jeffsenn** [CarlosNZ/json-edit-react#66]
**Describe the bug**
Empty string is a valid object key but is not allowed nor parsed correctly as input
Try to add a key to a object named "" (the empty string)
Or provide such an object value as input in code (and then editting that value produces an error)

**Expected behavior**
Empty string should work like every other valid key

**Screenshots**
Not required

**Online demo**
Not required

**Comment by CarlosNZ** [comment]
Good catch, thanks. Will look into it.

**Comment by CarlosNZ** [comment]
Hi @jeffsenn, this should be fixed now. Please try v1.11.7.

This is how it appears by default, but you can change the `<empty string>` display by overriding the `jer-empty-string::after` CSS pseudo class:

<img width="373" alt="Screenshot 2024-06-10 at 11 49 33 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/5456533/51e75798-35d1-41d9-820e-94edb8dd844e">
