### ISSUE TITLE
`onUpdate` is not working

### ISSUE THREAD

**Issue by lokmannicholas** [CarlosNZ/json-edit-react#77]
when using `onUpdate` in typescript, it always shows this error.
![image](https://github.com/CarlosNZ/json-edit-react/assets/9138305/1e45f723-2eb1-4d41-b6bd-b0f2a1565701)

**Comment by CarlosNZ** [comment]
Thanks for letting me know. Which version of the component are you using. And can you provide an example of the onUpdate function?

**Comment by lokmannicholas** [comment]
"json-edit-react": "^1.12.0-rc1",

**Comment by iainrobertstbf** [comment]
I am getting a similar editor. I have tried a bunch of versions from 1.1.1 to latest and all have it, so probably on my end.

index.esm.js:1 Uncaught (in promise) TypeError: just_clone__WEBPACK_IMPORTED_MODULE_5___default(...) is not a function
    at updateDataObject (index.esm.js:1:1)
    at index.esm.js:1:1
    at Generator.next (<anonymous>)
    at index.esm.js:1:1
    at new Promise (<anonymous>)
    at __awaiter (index.esm.js:1:1)
    at onEdit (index.esm.js:1:1)
    at handleEdit (index.esm.js:1:1)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)

**Comment by CarlosNZ** [comment]
Hi, can either of you reproduce the error in this Sandbox: https://codesandbox.io/p/sandbox/json-edit-react-demo-g5qlym?file=%2Fsrc%2FApp.js ? (Just fork it and post the modified link here if you can)

I'd like to see a minimally reproducible example before I can do more.

Thanks.

**Comment by iainrobertstbf** [comment]
I forked the sample and it works. I suspect this somehow relates to the way its being imported/built in webpack (for me). If you google the error there are bunch of people talking about it, and it appears to relate to the way components are exported/imported. But its all a bit over my head.

**Comment by iainrobertstbf** [comment]
Looking at my error, it appears to be related to just-clone dependency, which I see this uses.

![image](https://github.com/CarlosNZ/json-edit-react/assets/153821146/e915cfe1-e96d-493a-b1aa-69f1d4c28e06)

**Comment by iainrobertstbf** [comment]
As a complete guess.
![image](https://github.com/CarlosNZ/json-edit-react/assets/153821146/87dc0106-1d40-4845-8c72-d49c7d40998e)

Should this be

import {clone} from 'just-clone'

**Comment by CarlosNZ** [comment]
> import {clone} from 'just-clone'

Seems like I'm using it correctly: https://www.npmjs.com/package/just-clone

The component is being bundled with "rollup" for publishing, but I admit I'm no expert in this area. Just having a bit of a look, I might be using the `external` setting incorrectly in the rollup config. I was under the impression that everyone's development environment would automatically install external dependencies of this component, but perhaps I have to explicitly declare them in `external`.

Just out of interest, if you manually install those dependencies yourself, does it work?

Here's a new build with that "external" change: 
[json-edit-react-v1.12.0-rc2.tgz](https://github.com/user-attachments/files/15861405/json-edit-react-v1.12.0-rc2.tgz)

You can install that directly with `npm install /localPath/folder/whatever/json-edit-react-v1.12.0-rc2.tgz`. Let me know if that helps at all?

Lastly, would you mind telling me what your development environment is? (Which React bundler/hot-reloader package? Using `yarn` or `npm`?, etc..) I'd like to replicate several different environments on my system to be able to notice these kind of problems earlier.

**Comment by CarlosNZ** [comment]
> If you google the error there are bunch of people talking about it

Ha, this is news to me! I can't see much when I google it. Would you mind sharing your Google search?

**Comment by iainrobertstbf** [comment]
I googled this:

> webpack_imported_module_5___default(...) is not a function

Thanks I'll try above. I agree it appears you are using it correctly. 

I did try installing directly and I had the same issue.

I am using yarn, and webpack. Someone else set it up, I'm not sure what hot loader I'm using.

I am vaguely trying this fix: https://github.com/babel/babel/issues/12888#issuecomment-785016029

**Comment by iainrobertstbf** [comment]
Adding cjs to the following fixed it for me. 

![image](https://github.com/CarlosNZ/json-edit-react/assets/153821146/517f8fc5-3a71-475a-b2df-43d93b2d61a9)

**Comment by CarlosNZ** [comment]
> Adding cjs to the following fixed it for me.

Ah, interesting, thanks for sharing. I guess there's not a lot more I can do at my end -- hopefully your insight helps @lokmannicholas and anyone else who stumbles across this.

**Comment by lokmannicholas** [comment]
Thanks a lot @CarlosNZ  and @iainrobertstbf
