### ISSUE TITLE
Validating data through schema

### ISSUE THREAD

**Issue by SanderKok01** [CarlosNZ/json-edit-react#83]
Hi,

Firstly, thank you for implementing the drag and drop feature!

I have a question, is it possible to validate the data within the editor by using a `JSONSchema` or anything similar?
I have need of this in my project, so I'd like to know if this is available!

**Comment by CarlosNZ** [comment]
I do want to implement full JSON schema validation at some point, but it's a long term plan.

But you should be able to use an external validator like [jsonschema](https://www.npmjs.com/package/jsonschema) and pass an [`onUpdate`](https://github.com/CarlosNZ/json-edit-react?tab=readme-ov-file#update-functions) function to json-edit-react that sends the full data object to the validator and returns an error string if it doesn't pass (and then the data won't be updated).

Something like:

```js
onUpdate={ ( {newData} => 
  const result = validate(newData))
  // Not sure the actual syntax and return format of schema validator, but you get the idea...
  if (!result) {
   return "Does not comply with JSON schema" // this would show up in component UI as error
  }
}
```

It's a good use case though, I think I might update my [demo site](https://carlosnz.github.io/json-edit-react/) to include an example that validates against a JSON schema using this technique.

**Comment by SanderKok01** [comment]
Awesome, thanks!
