### ISSUE TITLE
Accept a "loading" prop and display "Loading" in UI

### ISSUE THREAD

**Issue by CarlosNZ** [CarlosNZ/json-edit-react#9]
Maybe other states, too. For example, a "disabled" state at which time it can't be edited.

**Comment by CarlosNZ** [comment]
Not needed. Parent should handle this and only render JsonEditor if data is ready.

**Comment by simeonackermann** [comment]
Hey, in my case I would really love to have a kind of init/loading state of the JSON component. Because my data is already present but the initiation of the json-react component needs quite a while ...! May it happens if the JSON data is a little bigger?!

**Comment by CarlosNZ** [comment]
@simeonackermann How big is your data? I haven't seen any significant time taken for the initial render? If you have a really enormous data set, you might want to set the initial `collapse` value to something quite low. Nodes that are collapsed on load don't have their contents rendered at all, so will siginificantly speed up initial rendering.

**Comment by simeonackermann** [comment]
Hm, I think the data is not too big; its about 22KB with 1000 loc

But I recognized that the React DEV process is massive slower than the productive build. And also reducing the collapse helped.

Thanks so far for the support!

**Comment by CarlosNZ** [comment]
@simeonackermann I decided not to implement this as it's very easy to do yourself using `React.lazy`:

https://react.dev/reference/react/lazy
