### ISSUE TITLE
Add custom "Key" elements possibility

### ISSUE THREAD

**Issue by MattChowski** [CarlosNZ/json-edit-react#91]
Hey there!

First of all, great library, absolutely love it.

We have a lot of ways to implement custom value nodes, but no way to edit the key element. Given this demo JSON:

```
arrayTest: [
  { 
      name: "",
      desc: 'test2' },
  { 
      name: 'lol', 
      desc: "" },
];
```
    
I would like to change how "name" and "desc" is displayed, not just CSS or text value, but get full control like value nodes. In my case, I would need the ":" (colon) symbol to go away if the value of that property is null or an empty string, so the final JSON display would be like:

```
arrayTest: [
  { 
      name, 
      desc: 'test2' },
  { 
      name: 'lol', 
      desc },
];
```

Is there a possibility to do this already that I am missing?

Thanks in advance!

**Comment by CarlosNZ** [comment]
Hi, thanks for your post.

You're right, it's not the easiest to specifically target the `key` value. However, if I understand you correctly, I think you can get pretty close to what you want with custom node definitions by setting the `hideKey: true` prop and then conditionally rendering the key yourself in the custom node.

Something like this:
```jsx
customNodeDefinitions={ [
  {
    condition: ({ value }) => value === '',
    element: ({ nodeData }) => {
      return <span style={{ marginLeft: '-0.5em' }}>{nodeData.key}</span>
    },
    hideKey: true,
  },
] },
```

I haven't put the commas in, not sure if that was what you wanted or not, but I think it would be straightforward to do so if you did. 

Does that get you closer to what you're after?

**Comment by CarlosNZ** [comment]
Cool, glad it's working for you :)
